server {
    listen 80;
    server_name web.au-team.irpo;
    
    location / {
        proxy_pass http://172.16.1.2:8080
    }
    
}

server {
    listen 80;
    server_name docker.au-team.irpo;
    
    location / {
        proxy_pass http://172.16.2.2:8080
    }
    
}
